from __future__ import annotations


class ReasonCodes:
    NO_RULE_MATCH = "NO_RULE_MATCH"
    FALLBACK_PATH = "FALLBACK_PATH"

    RULE_MATCHED = "RULE_MATCHED"
    PRIMARY_MODULE_SELECTED = "PRIMARY_MODULE_SELECTED"

    ALLOWED_MODULES_FILTER_APPLIED = "ALLOWED_MODULES_FILTER_APPLIED"
    NO_ELIGIBLE_MODULES = "NO_ELIGIBLE_MODULES"
    REGISTRY_INCONSISTENCY = "REGISTRY_INCONSISTENCY"

    COMPOSITION_ENABLED = "COMPOSITION_ENABLED"
    SINGLE_MODULE_PATH = "SINGLE_MODULE_PATH"

    PREVIEW_MODE = "PREVIEW_MODE"
    HANDOFF_MODE = "HANDOFF_MODE"
    HANDOFF_REQUIRED = "HANDOFF_REQUIRED"

    ACTIVE_MODULE_SELECTED = "ACTIVE_MODULE_SELECTED"
    BETA_MODULE_SELECTED = "BETA_MODULE_SELECTED"
    PLANNED_MODULE_SELECTED = "PLANNED_MODULE_SELECTED"