from app.models.registry import (
    RegistryDef,
    ModuleDef,
    CapabilityDef,
    IntentRule,
)
from app.registry.cryptolink_execution_capabilities import (
        CRYPTOLINK_EXECUTION_CAPABILITIES,
    )

REGISTRY = RegistryDef(
    modules=[
        ModuleDef(
            module_id="cryptolink",
            name="CryptoLink",
            description="Crypto market data, snapshots, trends and market signals.",
            status="active",
            version="v1",
            tags=["crypto", "market", "prices", "trends", "signals"],
            capabilities=[
                "crypto.price_lookup",
                "crypto.multi_asset_snapshot",
                "crypto.market_trend_summary",
                "crypto.market_regime_summary",
                *[cap.capability_id for cap in CRYPTOLINK_EXECUTION_CAPABILITIES],
            ],
            input_modes=["text", "symbol_list"],
            output_modes=["summary", "composed_summary", "preview", "tool_execution"],
            supports_handoff=True,
        ),
        ModuleDef(
            module_id="evilink_overview",
            name="Evilink",
            description="Overview module for the Evilink ecosystem, products and general platform orientation.",
            status="active",
            version="v1",
            tags=["ecosystem", "platform", "overview", "products", "evilink"],
            capabilities=[
                "ecosystem.platform_overview",
                "ecosystem.product_catalog_overview",
            ],
            input_modes=["text"],
            output_modes=["summary", "module_recommendation"],
            supports_handoff=False,
        ),
        ModuleDef(
            module_id="v_secrets",
            name="V-Secrets",
            description="Secrets, key management and cryptographic protection workflows.",
            status="active",
            version="v1",
            tags=["secrets", "keys", "cryptography", "security", "configuration"],
            capabilities=[
                "security.secret_storage",
                "security.key_management",
                "security.cryptographic_protection",
            ],
            input_modes=["text", "structured_input"],
            output_modes=["summary", "module_recommendation"],
            supports_handoff=True,
        ),
        ModuleDef(
            module_id="status_hub",
            name="Status-Hub",
            description="Ecosystem observability surface for service status and operational health visibility.",
            status="active",
            version="v1",
            tags=["observability", "status", "health", "monitoring", "ecosystem"],
            capabilities=[
                "ops.service_status_monitoring",
                "ops.ecosystem_health_visibility",
            ],
            input_modes=["text"],
            output_modes=["summary", "module_recommendation"],
            supports_handoff=False,
        ),
        ModuleDef(
            module_id="social_link",
            name="Social Link",
            description="Social and attention-oriented signals for topics, assets or communities.",
            status="beta",
            version="v0",
            tags=["social", "sentiment", "attention", "topics"],
            capabilities=[
                "social.topic_attention",
                "social.sentiment_summary",
            ],
            input_modes=["text", "topic"],
            output_modes=["summary", "preview"],
            supports_handoff=True,
        ),
        ModuleDef(
            module_id="curpify",
            name="Curpify",
            description="Validation-oriented module for CURP and RFC workflows in Mexico.",
            status="active",
            version="v1.5",
            tags=["validation", "identity", "curp", "rfc", "mexico", "tax"],
            capabilities=[
                "identity.curp_validation",
                "identity.rfc_validation",
                "identity.validation_explanation",
            ],
            input_modes=["text", "structured_input"],
            output_modes=["summary", "module_recommendation"],
            supports_handoff=True,
        ),
        ModuleDef(
            module_id="datalink",
            name="DataLink",
            description="Structured file processing, cleanup, deduplication and light transformation workflows.",
            status="active",
            version="v1",
            tags=["data", "processing", "cleanup", "deduplication", "files", "transform"],
            capabilities=[
                "data.ingestion_summary",
                "data.processing_recommendation",
                "data.structured_cleanup",
            ],
            input_modes=["text", "file_metadata", "structured_input"],
            output_modes=["summary", "composed_summary", "handoff"],
            supports_handoff=True,
        ),
        ModuleDef(
            module_id="vision_link",
            name="Vision Link",
            description="Vision-oriented analysis module for image-related workflows.",
            status="planned",
            version="v0",
            tags=["vision", "image", "analysis"],
            capabilities=[
                "vision.image_analysis_preview",
            ],
            input_modes=["text", "image_metadata"],
            output_modes=["preview", "handoff"],
            supports_handoff=True,
        ),
        ModuleDef(
            module_id="secure_link",
            name="Secure Link",
            description="Risk and trust evaluation module for fraud and security decisioning.",
            status="planned",
            version="v0",
            tags=["security", "risk", "fraud", "trust"],
            capabilities=[
                "security.risk_evaluation_preview",
                "security.decision_support_preview",
            ],
            input_modes=["text", "structured_input"],
            output_modes=["preview", "handoff"],
            supports_handoff=True,
        ),
    ],
    capabilities=[
        CapabilityDef(
            capability_id="crypto.price_lookup",
            module_id="cryptolink",
            name="Price Lookup",
            description="Returns price-oriented guidance or recommendation for crypto asset lookup scenarios.",
            exposure="public",
            tags=["price", "quote", "asset"],
            intent_families=["asset_lookup", "market_lookup"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="ecosystem.platform_overview",
            module_id="evilink_overview",
            name="Platform Overview",
            description="Explains what Evilink is and how the ecosystem is organized.",
            exposure="public",
            tags=["ecosystem", "platform", "overview"],
            intent_families=["ecosystem_overview"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="ecosystem.product_catalog_overview",
            module_id="evilink_overview",
            name="Product Catalog Overview",
            description="Explains the main products available inside the Evilink ecosystem.",
            exposure="public",
            tags=["ecosystem", "products", "catalog"],
            intent_families=["ecosystem_overview", "product_catalog"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="crypto.multi_asset_snapshot",
            module_id="cryptolink",
            name="Multi Asset Snapshot",
            description="Summarizes multiple assets or a selected market slice.",
            exposure="public",
            tags=["snapshot", "market", "multi-asset"],
            intent_families=["market_snapshot", "market_summary"],
            output_modes=["summary", "composed_summary"],
        ),
        CapabilityDef(
            capability_id="crypto.market_trend_summary",
            module_id="cryptolink",
            name="Market Trend Summary",
            description="Explains short trend-oriented market context.",
            exposure="public",
            tags=["trend", "market", "summary"],
            intent_families=["trend_analysis", "market_summary"],
            output_modes=["summary", "composed_summary"],
        ),
        CapabilityDef(
            capability_id="crypto.market_regime_summary",
            module_id="cryptolink",
            name="Market Regime Summary",
            description="Provides regime-level interpretation of market conditions.",
            exposure="preview",
            tags=["regime", "signals", "market"],
            intent_families=["market_regime", "trend_analysis"],
            output_modes=["preview", "summary"],
            restrictions=["May rely on beta market signal interpretation."],
        ),
        CapabilityDef(
            capability_id="social.topic_attention",
            module_id="social_link",
            name="Topic Attention",
            description="Explains attention or buzz around a topic or asset.",
            exposure="preview",
            tags=["attention", "topic", "buzz"],
            intent_families=["topic_attention", "trend_analysis"],
            output_modes=["preview", "summary"],
        ),
        CapabilityDef(
            capability_id="social.sentiment_summary",
            module_id="social_link",
            name="Sentiment Summary",
            description="Summarizes light sentiment-style interpretation for a topic or asset.",
            exposure="preview",
            tags=["sentiment", "social", "topic"],
            intent_families=["sentiment_analysis", "topic_attention"],
            output_modes=["preview", "summary"],
        ),
        CapabilityDef(
            capability_id="identity.curp_validation",
            module_id="curpify",
            name="CURP Validation",
            description="Determines if a validation use case maps to CURP-oriented workflows.",
            exposure="public",
            tags=["curp", "validation", "identity"],
            intent_families=["identity_validation", "curp_validation"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="identity.rfc_validation",
            module_id="curpify",
            name="RFC Validation",
            description="Determines if a validation use case maps to RFC-oriented workflows with check digit verification.",
            exposure="public",
            tags=["rfc", "validation", "tax", "mexico"],
            intent_families=["tax_validation", "rfc_validation", "identity_validation"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="identity.validation_explanation",
            module_id="curpify",
            name="Validation Explanation",
            description="Explains whether a CURP or RFC validation workflow is the best fit for the request.",
            exposure="public",
            tags=["validation", "explanation", "curp", "rfc"],
            intent_families=["identity_validation", "capability_explanation", "rfc_validation", "tax_validation"],
            output_modes=["summary", "capability_explanation"],
        ),
        CapabilityDef(
            capability_id="data.ingestion_summary",
            module_id="datalink",
            name="Data Ingestion Summary",
            description="Structured file processing, cleanup, deduplication and transformation workflows for CSV and JSON datasets.",
            exposure="public",
            tags=["data", "ingestion", "pipeline", "files"],
            intent_families=["data_ingestion", "pipeline_request"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="data.processing_recommendation",
            module_id="datalink",
            name="Data Processing Recommendation",
            description="Recommends structured cleanup, deduplication, filtering and transformation workflows.",
            exposure="public",
            tags=["processing", "transform", "cleanup", "deduplication", "data"],
            intent_families=["data_processing", "pipeline_request", "structured_cleanup"],
            output_modes=["summary", "handoff"],
        ),
        CapabilityDef(
            capability_id="data.structured_cleanup",
            module_id="datalink",
            name="Structured Cleanup",
            description="Explains cleanup-oriented workflows for CSV, JSON and structured datasets at scale. including deduplication, filtering and light transformation",
            exposure="public",
            tags=["cleanup", "csv", "json", "structured", "dataset"],
            intent_families=["structured_cleanup", "data_processing"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="vision.image_analysis_preview",
            module_id="vision_link",
            name="Image Analysis Preview",
            description="Preview-only capability for image-oriented analysis workflows.",
            exposure="preview",
            tags=["vision", "image", "preview"],
            intent_families=["image_analysis", "vision_request"],
            output_modes=["preview", "handoff"],
            restrictions=["Planned capability; not active yet."],
        ),
        CapabilityDef(
            capability_id="security.risk_evaluation_preview",
            module_id="secure_link",
            name="Risk Evaluation Preview",
            description="Preview-only capability for risk evaluation and trust scoring flows.",
            exposure="handoff_only",
            tags=["security", "risk", "fraud"],
            intent_families=["risk_evaluation", "fraud_detection"],
            output_modes=["handoff", "preview"],
            restrictions=["Planned capability; requires future security engine."],
        ),
        CapabilityDef(
            capability_id="security.decision_support_preview",
            module_id="secure_link",
            name="Decision Support Preview",
            description="Preview-only capability for allow/challenge/block style reasoning.",
            exposure="handoff_only",
            tags=["decision", "security", "trust"],
            intent_families=["decision_support", "risk_evaluation"],
            output_modes=["handoff", "preview"],
            restrictions=["Planned capability; not exposed as active logic yet."],
        ),
        CapabilityDef(
            capability_id="security.secret_storage",
            module_id="v_secrets",
            name="Secret Storage",
            description="Explains secure secret storage workflows for tokens, credentials and sensitive configuration.",
            exposure="public",
            tags=["secrets", "storage", "credentials"],
            intent_families=["secrets_management", "secure_configuration"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="security.key_management",
            module_id="v_secrets",
            name="Key Management",
            description="Explains workflows for managing keys and sensitive integration material.",
            exposure="public",
            tags=["keys", "management", "security"],
            intent_families=["key_management", "secrets_management"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="security.cryptographic_protection",
            module_id="v_secrets",
            name="Cryptographic Protection",
            description="Explains cryptographic protection use cases for sensitive data and service configuration.",
            exposure="public",
            tags=["cryptography", "protection", "security"],
            intent_families=["cryptographic_protection", "secure_configuration"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="ops.service_status_monitoring",
            module_id="status_hub",
            name="Service Status Monitoring",
            description="Explains service status visibility for ecosystem APIs and services.",
            exposure="public",
            tags=["status", "monitoring", "services"],
            intent_families=["service_status", "observability"],
            output_modes=["summary", "module_recommendation"],
        ),
        CapabilityDef(
            capability_id="ops.ecosystem_health_visibility",
            module_id="status_hub",
            name="Ecosystem Health Visibility",
            description="Explains operational health visibility across the ecosystem.",
            exposure="public",
            tags=["health", "observability", "ecosystem"],
            intent_families=["ecosystem_health", "observability"],
            output_modes=["summary", "module_recommendation"],
        ),
        *CRYPTOLINK_EXECUTION_CAPABILITIES, 
    ],

    intent_rules=[
        IntentRule(
            rule_id="rule_asset_lookup_crypto",
            intent_family="asset_lookup",
            description="Routes asset and quote requests to CryptoLink price execution.",
            priority="high",
            patterns=[
                "price", "prices", "precios", "price lookup", "precio de", "precios de","cuanto valen",
                "cuánto valen", "cotizacion","cotización","cotizaciones", "quote", "market price", "btc price", "eth price", "price of",
                "precio", "cotiza", "valor", "cuanto vale", "cuánto vale",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.prices"],   # antes: crypto.price_lookup
            allow_composition=False,
        ),

        # --- Snapshot / resumen general (antes -> multi_asset_snapshot + trend_summary) ---
        IntentRule(
            rule_id="rule_market_summary_crypto",
            intent_family="market_snapshot_exec",
            description="Routes general market snapshot/overview to CryptoLink snapshot execution.",
            priority="high",
            patterns=[
                "market snapshot", "market summary", "market overview", "snapshot",
                "overview", "how is the market", "crypto market",
                "resumen del mercado", "estado del mercado", "panorama del mercado",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.snapshot"],   # antes: recomendación
            allow_composition=False,
        ),

        # --- Trends (tendencia) ---
        IntentRule(
            rule_id="rule_market_trends_crypto",
            intent_family="market_trends_exec",
            description="Routes market trend requests to CryptoLink trends execution.",
            priority="high",
            patterns=[
                "market trends", "market trend", "trend", "trends",
                "tendencia del mercado", "tendencia de mercado", "tendencias",
                "tendencia reciente",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.trends"],
            allow_composition=False,
        ),

        # --- Momentum ---
        IntentRule(
            rule_id="rule_market_momentum_crypto",
            intent_family="market_momentum_exec",
            description="Routes momentum requests to CryptoLink momentum execution.",
            priority="high",
            patterns=[
                "momentum", "market momentum", "fuerza del mercado", "traccion",
                "tracción", "strength",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.momentum"],
            allow_composition=False,
        ),

        # --- Regime (régimen) ---
        IntentRule(
            rule_id="rule_market_regime_crypto",
            intent_family="market_regime_exec",
            description="Routes market regime requests to CryptoLink regime execution.",
            priority="high",
            patterns=[
                "market regime", "régimen del mercado", "regimen del mercado",
                "régimen de mercado", "regimen de mercado", "sesgo del mercado",
                "market bias",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.regime"],
            allow_composition=False,
        ),

        # --- Market health ---
        IntentRule(
            rule_id="rule_market_health_crypto",
            intent_family="market_health_exec",
            description="Routes market health requests to CryptoLink health execution.",
            priority="high",
            patterns=[
                "market health", "salud del mercado", "salud de mercado",
                "market condition", "condicion del mercado", "condición del mercado",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.market_health"],
            allow_composition=False,
        ),

        # --- Anomalies ---
        IntentRule(
            rule_id="rule_market_anomalies_crypto",
            intent_family="market_anomalies_exec",
            description="Routes anomaly detection to CryptoLink anomalies execution.",
            priority="high",
            patterns=[
                "market anomalies", "anomalias del mercado", "anomalías del mercado",
                "movimiento inusual", "movimientos inusuales", "actividad inusual",
                "outliers", "detectar anomalias", "detectar anomalías",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.anomalies"],
            allow_composition=False,
        ),

         # --- Risk flags de MERCADO (gana a secure_link por especificidad) ---
        IntentRule(
            rule_id="rule_market_risk_flags_crypto",
            intent_family="market_risk_flags_exec",
            description="Routes MARKET risk flags to CryptoLink (distinct from fraud/security -> secure_link).",
            priority="critical",
            patterns=[
                "risk flags", "risk signals", "market risk",
                "riesgo de mercado", "riesgo del mercado", "riesgos de mercado",
                "banderas de riesgo", "señales de riesgo", "alertas de mercado",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.risk_flags"],
            allow_composition=False,
        ),

        # --- Social pulse / narrativa ---
        IntentRule(
            rule_id="rule_market_social_pulse_crypto",
            intent_family="market_narrative_exec",
            description="Routes social pulse / market narrative to CryptoLink execution.",
            priority="high",
            patterns=[
                "social pulse", "market narrative", "pulso social",
                "narrativa del mercado", "narrativa de mercado",
                "sentimiento del mercado", "social sentiment",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.social_pulse"],
            allow_composition=False,
        ),

        # --- Movers ---
        IntentRule(
            rule_id="rule_market_movers_crypto",
            intent_family="market_movers_exec",
            description="Routes top movers to CryptoLink movers execution.",
            priority="high",
            patterns=[
                "top movers", "market movers", "biggest movers",
                "mayores subidas", "mayores caidas", "mayores caídas",
                "gainers", "losers",
            ],
            preferred_modules=["cryptolink"],
            preferred_capabilities=["crypto.exec.movers"],
            allow_composition=False,
        ),

        IntentRule(
            rule_id="rule_ecosystem_what_is_evilink",
            intent_family="ecosystem_overview",
            description="Explains what Evilink is.",
            priority="high",
            patterns=[
                "what is evilink",
                "what's evilink",
                "que es evilink",
                "qué es evilink",
                "explica evilink",
                "explain evilink",
            ],
            preferred_modules=["evilink_overview"],
            preferred_capabilities=["ecosystem.platform_overview"],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_ecosystem_products_evilink",
            intent_family="product_catalog",
            description="Explains what products exist inside Evilink.",
            priority="high",
            patterns=[
                "que productos tiene evilink",
                "qué productos tiene evilink",
                "what products are in evilink",
                "what can i do in evilink",
                "ecosistema evilink",
                "evilink overview",
            ],
            preferred_modules=["evilink_overview"],
            preferred_capabilities=["ecosystem.product_catalog_overview"],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_trend_analysis_composed",
            intent_family="trend_analysis",
            description="Allows light composition between CryptoLink and Social Link for trend context.",
            priority="medium",
            patterns=[
                "trend",
                "momentum",
                "attention",
                "sentiment",
                "tendencia",
                "fuerza",
                "narrativa",
            ],
            preferred_modules=["cryptolink", "social_link"],
            preferred_capabilities=[
                "crypto.market_trend_summary",
                "social.topic_attention",
            ],
            allow_composition=True,
        ),
        IntentRule(
            rule_id="rule_identity_validation_curpify",
            intent_family="identity_validation",
            description="Routes CURP and identity validation requests to Curpify.",
            priority="critical",
            patterns=[
                "curp",
                "validar curp",
                "validate curp",
                "validate identity",
                "identity validation",
                "validation",
                "mexico id",
                "identidad mexico",
            ],
            preferred_modules=["curpify"],
            preferred_capabilities=[
                "identity.curp_validation",
                "identity.validation_explanation",
            ],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_rfc_validation_curpify",
            intent_family="rfc_validation",
            description="Routes RFC validation requests to Curpify.",
            priority="critical",
            patterns=[
                "rfc",
                "validate rfc",
                "rfc validation",
                "validar rfc",
                "tax id mexico",
                "digito verificador",
                "dígito verificador",
                "check digit",
                "que es curpify",
                "what is curpify",
            ],
            preferred_modules=["curpify"],
            preferred_capabilities=[
                "identity.rfc_validation",
                "identity.validation_explanation",
            ],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_data_ingestion_datalink",
            intent_family="data_ingestion",
            description="Routes ingestion-oriented requests to Data_Link.",
            priority="high",
            patterns=[
                "upload",
                "ingest",
                "import",
                "process file",
                "file upload",
                "dataset upload",
                "subir archivo",
                "importar archivo",
                "cargar archivo",
                "ingestar datos",
            ],
            preferred_modules=["datalink"],
            preferred_capabilities=["data.ingestion_summary"],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_data_processing_datalink",
            intent_family="data_processing",
            description="Routes file processing and transformation requests to Data_Link.",
            priority="high",
            patterns=[
                "data_link",
                "datalink",
                "transform",
                "transformar",
                "filter",
                "filtrar",
                "pipeline",
                "dataset",
                "procesar datos",
                "procesar csv",
                "procesar json",
                "sirve para",
                "para que sirve",
            ],
            preferred_modules=["datalink"],
            preferred_capabilities=[
                "data.processing_recommendation",
                "data.structured_cleanup",
            ],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_structured_cleanup_datalink",
            intent_family="structured_cleanup",
            description="Routes structured cleanup and file cleaning requests to Data_Link.",
            priority="high",
            patterns=[
                "cleanup",
                "clean file",
                "deduplicate",
                "csv cleanup",
                "json cleanup",
                "structured file cleanup",
                "limpiar csv",
                "limpiar json",
                "limpiar datos",
                "depurar datos",
                "deduplicar",
                "transformar archivo",
                "csv",
                "json",
            ],
            preferred_modules=["datalink"],
            preferred_capabilities=[
                "data.structured_cleanup",
                "data.processing_recommendation",
            ],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_datalink_general_fit",
            intent_family="data_processing",
            description="Routes broad questions about cleaning or processing data to Data_Link.",
            priority="high",
            patterns=[
                "limpiar datos",
                "clean data",
                "procesar datos",
                "data cleaning",
                "data processing",
                "api para limpiar datos",
                "api para procesar datos",
                "hay alguna api para limpiar datos",
                "alguna api para limpiar datos",
                "ecosistema evilink para limpiar datos",
            ],
            preferred_modules=["datalink"],
            preferred_capabilities=[
                "data.processing_recommendation",
                "data.structured_cleanup",
            ],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_secrets_management_vsecrets",
            intent_family="secrets_management",
            description="Routes secrets and key-management requests to V-Secrets.",
            priority="high",
            patterns=[
                "secret",
                "secrets",
                "secret management",
                "secrets management",
                "management secrets",
                "secretos",
                "administrar secretos",
                "api key",
                "api keys",
                "keys",
                "credentials",
                "vault",
                "key management",
                "cryptography",
                "encriptacion",
                "encriptación",
                "llaves",
                "handles secrets",
                "app that handles secrets",
            ],
            preferred_modules=["v_secrets"],
            preferred_capabilities=[
                "security.secret_storage",
                "security.key_management",
            ],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_status_monitoring_statushub",
            intent_family="service_status",
            description="Routes service status and ecosystem health visibility requests to Status-Hub.",
            priority="high",
            patterns=[
                "status-hub",
                "status hub",
                "service status",
                "app status",
                "system status",
                "uptime",
                "monitoring",
                "incident",
                "incidencias",
                "observability",
                "observabilidad",
                "monitoreo",
                "salud operativa",
                "healthcheck",
                "health de apps",
            ],
            preferred_modules=["status_hub"],
            preferred_capabilities=[
                "ops.service_status_monitoring",
                "ops.ecosystem_health_visibility",
            ],
            allow_composition=False,
        ),
        IntentRule(
            rule_id="rule_image_analysis_vision_preview",
            intent_family="image_analysis",
            description="Routes image-oriented workflows to Vision Link as preview/handoff only.",
            priority="medium",
            patterns=[
                "image",
                "photo",
                "vision",
                "analyze image",
                "analizar imagen",
                "yolo",
            ],
            preferred_modules=["vision_link"],
            preferred_capabilities=["vision.image_analysis_preview"],
            allow_composition=False,
            handoff_if_unavailable=True,
            preview_if_planned=True,
        ),
        IntentRule(
            rule_id="rule_risk_eval_secure_preview",
            intent_family="risk_evaluation",
            description="Routes risk and security requests to Secure Link in preview/handoff mode.",
            priority="critical",
            patterns=[
                "risk",
                "fraud",
                "fraud detection",
                "transaction risk",
                "security risk",
                "trust score",
                "decision support",
                "riesgo",
                "fraude",
            ],
            preferred_modules=["secure_link"],
            preferred_capabilities=[
                "security.risk_evaluation_preview",
                "security.decision_support_preview",
            ],
            allow_composition=False,
            handoff_if_unavailable=True,
            preview_if_planned=True,
        ),
    ]
)